/*
 * Enum constants for different locations
 * Used in class Location
 */
public enum Locations {
	MINER_EAST_VARROCK, MINER_LUMBRIDGE, MINER_WEST_VARROCK, MINER_DWARVEN_MINE_COAL, 
	SMELTER_AL_KHARID, SMITHING_WEST_VARROCK, FISHING_AL_KHARID, FISHING_BARBARIAN_VILLAGE, 
	COOKING_AL_KHARID, COMBAT_GIANT_FROG, COMBAT_BARBARIAN, MINER_CRAFTING_GUILD_GOLD, SPLASHING_BEAR,
	SMELTER_EDGEVILLE, FISHING_CATHERBY, COMBAT_EXPERIMENTS, COOKING_CATHERBY
}
